### ISSUE TITLE
Code is not licensed - is it open source?

### ISSUE THREAD

**Issue by jwakely** [bsl/send-sds#2]
Hi, I see there's no license file in the repo, so if I fork it to make any improvements I'm violating your copyright, which I assume is not your intention.

See https://help.github.com/articles/licensing-a-repository/ for more explanation, and https://help.github.com/articles/adding-a-license-to-a-repository/ for the easiest way to add one to a Github repo.

**Comment by bsl** [comment]
@jwakely Hi, I added a license file. Thanks.

**Comment by jwakely** [comment]
Wow that was quick, thanks!
